markdown: rdiscount
pygments: true
permalink: pretty
url: http://benediktmeurer.de
title: Benedikt Meurer
slug: Software Developer, Research Associate
author: Benedikt Meurer
email: http://www.google.com/recaptcha/mailhide/d?k=01MJgavN3AFGU2lZgtX4GZQg==&c=EmtLZgyvbIomD3RRoocY2vZjay4Q1-2j5VGLE5fp_rI=
atom: http://feeds.feedburner.com/bmeurer
